# Project: 260408-2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 260408-2.o Date.o Dog.o
LINKOBJ  = 260408-2.o Date.o Dog.o
LIBS     = -L"C:/PortableApps/DevCppPortable/MinGW64/lib" -L"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/PortableApps/DevCppPortable/MinGW64/include" -I"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/PortableApps/DevCppPortable/MinGW64/include" -I"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 260408-2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

260408-2.o: 260408-2.cpp
	$(CPP) -c 260408-2.cpp -o 260408-2.o $(CXXFLAGS)

Date.o: Date.cpp
	$(CPP) -c Date.cpp -o Date.o $(CXXFLAGS)

Dog.o: Dog.cpp
	$(CPP) -c Dog.cpp -o Dog.o $(CXXFLAGS)
