# Project: ±M®×1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 260401-2.o pet.o
LINKOBJ  = 260401-2.o pet.o
LIBS     = -L"C:/PortableApps/DevCppPortable/MinGW64/lib" -L"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/PortableApps/DevCppPortable/MinGW64/include" -I"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/PortableApps/DevCppPortable/MinGW64/include" -I"C:/PortableApps/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/PortableApps/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

260401-2.o: 260401-2.cpp
	$(CPP) -c 260401-2.cpp -o 260401-2.o $(CXXFLAGS)

pet.o: pet.cpp
	$(CPP) -c pet.cpp -o pet.o $(CXXFLAGS)
